server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: shop_ecommerce
  # se deccomentti queste 2 righe crea lo schema del db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shop?zeroDateTimeBehavior=Round&serverTimezone=Europe/Rome
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500KB
      max-request-size: 500KB
shop:
  frontendurl: http://localhost:4200
  baseurl: ${shop.frontendurl}
  jwt:
    secret: ants
    tokenvalidityinhours: 12

paypal:
  mode: sandbox
  account: sb-c8tvt13908975@business.example.com
  client:
    id: AUOZZ4Wzxe0k2CkkxquC9U3rw1KMaBGhs09uxD-ndmpaFoOyJ1Hc29WyIPSZX-Iuh4TTjWi10fSPdpgX
    secret: EM5NzXUOHlOkLht-M0N_qlUaSn7QOMAxgvEcgwi0snarSg0xr56tNVy-R87YhQj6BA2lJo_6GVfP3qtF

braintree:
  merchantId: yyykmfh54fjwpjfh
  publicKey: 2ndtf7qdn4km879s
  privateKey: 550e45cc806c18c6411ab3fb772d754f