server:
  port: 8080
spring:
  application:
    name: shop_ecommerce
  # se deccomentti queste 2 righe crea lo schema del db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?zeroDateTimeBehavior=Round&serverTimezone=Europe/Rome
    #    url: jdbc:mysql://192.168.1.254:3308/ants?zeroDateTimeBehavior=Round
    username: root
    password: landmark123@
  servlet:
    multipart:
      enabled: true
      max-file-size: 500KB
      max-request-size: 500KB
shop:
  frontendurl: http://localhost:4200
  baseurl: ${shop.frontendurl}
  jwt:
    secret: ants
    tokenvalidityinhours: 12
  storage:
    path: storage
    resourcepath: file:/storage/
    imagesfolder: images
    videosfolder: videos
  logging:
    resourcepath: file:///E:/ants/logging/
    logfilepath: E:\ants\logging
